# 101 kitten carousel static web site project

AWSTemplateFormatVersion: 2010-09-09
Description: |
Kittens Carousel static website
  
 
Resources:

CFN_ApacheWebServer:
  Type: AWS::EC2::Instance
  Properties:
    
    ImageId: ami-0a8b4cd432b1c3063
    InstanceType: t2.micro
    KeyName: firstkey.pem
    SecurityGroups:
      - cfn-sec-group

    Tags:
      - Key: Name
      - Value: Kitten-Carousel

    UserData: "String"
    Volumes:
      Volumes

Transform:
  
Outputs:
